# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 07:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('product_id', models.TextField(max_length=255)),
                ('price', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=1500)),
                ('size', django.contrib.postgres.fields.jsonb.JSONField()),
                ('color', django.contrib.postgres.fields.jsonb.JSONField()),
                ('main_image', models.TextField(max_length=255)),
                ('images', django.contrib.postgres.fields.jsonb.JSONField()),
                ('video', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
