# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20160922_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name': 'Product_Category', 'verbose_name_plural': 'Product_Categories'},
        ),
    ]
