# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
