# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20161009_0412'),
        ('transaction', '0002_auto_20161017_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='product',
        ),
        migrations.AddField(
            model_name='order_item',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
