# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20161009_0412'),
        ('transaction', '0003_auto_20161017_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='product',
        ),
        migrations.AddField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
