# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_billing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_address_id',
        ),
        migrations.AddField(
            model_name='user',
            name='default_billing_address',
            field=models.CharField(blank=True, max_length=30, verbose_name='default_billing_address'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_shipping_address',
            field=models.CharField(blank=True, max_length=30, verbose_name='default_shipping_address'),
        ),
    ]
