# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20160921_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='username'),
        ),
    ]
