# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20161014_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_billing_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='default_billing_address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_shipping_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='default_shipping_address'),
        ),
    ]
