# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_auto_20161014_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newPassword', models.CharField(blank=True, max_length=30, verbose_name='new_password')),
                ('renewPassword', models.CharField(blank=True, max_length=30, verbose_name='renew_password')),
            ],
        ),
    ]
