# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='address_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='address_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_billing',
            field=models.CharField(blank=True, max_length=30, verbose_name='default_billing'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='full_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.CharField(blank=True, max_length=30, verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='mpesa_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='mpesa_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='shipping_address_id'),
        ),
    ]
