# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_auto_20160921_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='full_name'),
        ),
    ]
