# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_auto_20160922_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mpesa_id',
            field=models.TextField(blank=True, max_length=30, verbose_name='mpesa_id'),
        ),
    ]
