# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20161009_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
