# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='owner',
        ),
    ]
