# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_fileupload_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='parent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='datafile',
            field=models.FileField(upload_to=products.models.makeImagePath),
        ),
    ]
