# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_fileupload_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='product',
        ),
    ]
