# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20161115_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='datafile',
        ),
    ]
