# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20161115_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datafile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.FileUpload'),
            preserve_default=False,
        ),
    ]
